# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/jordy/Documentos/cg/trabalho 2/ray_tracer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/jordy/Documentos/cg/trabalho 2/ray_tracer"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/jordy/Documentos/cg/trabalho 2/ray_tracer/CMakeFiles" "/home/jordy/Documentos/cg/trabalho 2/ray_tracer/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/jordy/Documentos/cg/trabalho 2/ray_tracer/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ray_tracer

# Build rule for target.
ray_tracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ray_tracer
.PHONY : ray_tracer

# fast build rule for target.
ray_tracer/fast:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/build
.PHONY : ray_tracer/fast

src/buffer.o: src/buffer.cpp.o

.PHONY : src/buffer.o

# target to build an object file
src/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/buffer.cpp.o
.PHONY : src/buffer.cpp.o

src/buffer.i: src/buffer.cpp.i

.PHONY : src/buffer.i

# target to preprocess a source file
src/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/buffer.cpp.i
.PHONY : src/buffer.cpp.i

src/buffer.s: src/buffer.cpp.s

.PHONY : src/buffer.s

# target to generate assembly for a file
src/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/buffer.cpp.s
.PHONY : src/buffer.cpp.s

src/camera.o: src/camera.cpp.o

.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i

.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s

.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/onb.o: src/onb.cpp.o

.PHONY : src/onb.o

# target to build an object file
src/onb.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/onb.cpp.o
.PHONY : src/onb.cpp.o

src/onb.i: src/onb.cpp.i

.PHONY : src/onb.i

# target to preprocess a source file
src/onb.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/onb.cpp.i
.PHONY : src/onb.cpp.i

src/onb.s: src/onb.cpp.s

.PHONY : src/onb.s

# target to generate assembly for a file
src/onb.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/onb.cpp.s
.PHONY : src/onb.cpp.s

src/orthographic_camera.o: src/orthographic_camera.cpp.o

.PHONY : src/orthographic_camera.o

# target to build an object file
src/orthographic_camera.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/orthographic_camera.cpp.o
.PHONY : src/orthographic_camera.cpp.o

src/orthographic_camera.i: src/orthographic_camera.cpp.i

.PHONY : src/orthographic_camera.i

# target to preprocess a source file
src/orthographic_camera.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/orthographic_camera.cpp.i
.PHONY : src/orthographic_camera.cpp.i

src/orthographic_camera.s: src/orthographic_camera.cpp.s

.PHONY : src/orthographic_camera.s

# target to generate assembly for a file
src/orthographic_camera.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/orthographic_camera.cpp.s
.PHONY : src/orthographic_camera.cpp.s

src/primitive.o: src/primitive.cpp.o

.PHONY : src/primitive.o

# target to build an object file
src/primitive.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/primitive.cpp.o
.PHONY : src/primitive.cpp.o

src/primitive.i: src/primitive.cpp.i

.PHONY : src/primitive.i

# target to preprocess a source file
src/primitive.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/primitive.cpp.i
.PHONY : src/primitive.cpp.i

src/primitive.s: src/primitive.cpp.s

.PHONY : src/primitive.s

# target to generate assembly for a file
src/primitive.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/primitive.cpp.s
.PHONY : src/primitive.cpp.s

src/ray.o: src/ray.cpp.o

.PHONY : src/ray.o

# target to build an object file
src/ray.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/ray.cpp.o
.PHONY : src/ray.cpp.o

src/ray.i: src/ray.cpp.i

.PHONY : src/ray.i

# target to preprocess a source file
src/ray.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/ray.cpp.i
.PHONY : src/ray.cpp.i

src/ray.s: src/ray.cpp.s

.PHONY : src/ray.s

# target to generate assembly for a file
src/ray.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/ray.cpp.s
.PHONY : src/ray.cpp.s

src/raytracer.o: src/raytracer.cpp.o

.PHONY : src/raytracer.o

# target to build an object file
src/raytracer.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/raytracer.cpp.o
.PHONY : src/raytracer.cpp.o

src/raytracer.i: src/raytracer.cpp.i

.PHONY : src/raytracer.i

# target to preprocess a source file
src/raytracer.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/raytracer.cpp.i
.PHONY : src/raytracer.cpp.i

src/raytracer.s: src/raytracer.cpp.s

.PHONY : src/raytracer.s

# target to generate assembly for a file
src/raytracer.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/raytracer.cpp.s
.PHONY : src/raytracer.cpp.s

src/scene.o: src/scene.cpp.o

.PHONY : src/scene.o

# target to build an object file
src/scene.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/scene.cpp.o
.PHONY : src/scene.cpp.o

src/scene.i: src/scene.cpp.i

.PHONY : src/scene.i

# target to preprocess a source file
src/scene.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/scene.cpp.i
.PHONY : src/scene.cpp.i

src/scene.s: src/scene.cpp.s

.PHONY : src/scene.s

# target to generate assembly for a file
src/scene.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/scene.cpp.s
.PHONY : src/scene.cpp.s

src/sphere.o: src/sphere.cpp.o

.PHONY : src/sphere.o

# target to build an object file
src/sphere.cpp.o:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/sphere.cpp.o
.PHONY : src/sphere.cpp.o

src/sphere.i: src/sphere.cpp.i

.PHONY : src/sphere.i

# target to preprocess a source file
src/sphere.cpp.i:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/sphere.cpp.i
.PHONY : src/sphere.cpp.i

src/sphere.s: src/sphere.cpp.s

.PHONY : src/sphere.s

# target to generate assembly for a file
src/sphere.cpp.s:
	$(MAKE) -f CMakeFiles/ray_tracer.dir/build.make CMakeFiles/ray_tracer.dir/src/sphere.cpp.s
.PHONY : src/sphere.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ray_tracer"
	@echo "... edit_cache"
	@echo "... src/buffer.o"
	@echo "... src/buffer.i"
	@echo "... src/buffer.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/onb.o"
	@echo "... src/onb.i"
	@echo "... src/onb.s"
	@echo "... src/orthographic_camera.o"
	@echo "... src/orthographic_camera.i"
	@echo "... src/orthographic_camera.s"
	@echo "... src/primitive.o"
	@echo "... src/primitive.i"
	@echo "... src/primitive.s"
	@echo "... src/ray.o"
	@echo "... src/ray.i"
	@echo "... src/ray.s"
	@echo "... src/raytracer.o"
	@echo "... src/raytracer.i"
	@echo "... src/raytracer.s"
	@echo "... src/scene.o"
	@echo "... src/scene.i"
	@echo "... src/scene.s"
	@echo "... src/sphere.o"
	@echo "... src/sphere.i"
	@echo "... src/sphere.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

